In [1]:
# !pip install numpy
# !pip install matplotlib

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Scalar

In [3]:
s = 10
s

10

# Wektor

In [4]:
# prosty wektor z listy
X = np.array([1, 2, 3])
X

array([1, 2, 3])

In [5]:
# opis wektora
print(f"Rozmiar:   {X.shape}")
print(f"Pojemność: {X.size}")
print(f"Wymiar:    {X.ndim}")

Rozmiar:   (3,)
Pojemność: 3
Wymiar:    1


In [6]:
# dostęp do elementów wektora
# element x1 -> index x[0]
X[0]

1

In [7]:
# wektor kolumnowy
Y = np.array([[1], [2], [3], [5.5]])
Y

array([[1. ],
       [2. ],
       [3. ],
       [5.5]])

# Macierz

Macierz to układ liczb, symboli lub wyrażeń zapisanych w postaci prostokątnej tablicy. Możemy myśleć o macierzy jako zbiorze wektorów.

In [8]:
# macierz
M = np.array([[1, 2, 3], [2, 3, 4]])
M

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
# opis macierzy
print(f"Rozmiar:   {M.shape}")
print(f"Pojemność: {M.size}")
print(f"Wymiar:    {M.ndim}")

Rozmiar:   (2, 3)
Pojemność: 6
Wymiar:    2


In [10]:
# dostęp do elementów macierzy 
M[0][2]
M[0, 2]

3

# Tensor

Tensor jako uogulnienie macierzy.

In [11]:
T = np.array([
              [[1, 2, 3.3], [2, 3, 4]], 
              [[1, 2, 5. ], [5, 5, 6]]
              ])
T

array([[[1. , 2. , 3.3],
        [2. , 3. , 4. ]],

       [[1. , 2. , 5. ],
        [5. , 5. , 6. ]]])

In [12]:
# opis tensora
print(f"Rozmiar:   {T.shape}")
print(f"Pojemność: {T.size}")
print(f"Wymiar:    {T.ndim}")

Rozmiar:   (2, 2, 3)
Pojemność: 12
Wymiar:    3


In [13]:
# dostęp do elementów tensora
T[0][1][1]
T[0, 1, 1]

3.0

# Generowanie liczb losowych

### Arange

In [ ]:
np.arange(0, 10, 1.1)     # np.arange(od, do, krok)
np.arange(-1.1, 10, 2.1)  # [-10; 10) - jako przedział od -1.1 domknięty (włącznie) do 10 otwarty (bez)

### linspace

In [ ]:
np.linspace(0, 1, 100)      # np.linspace(od, do, ile_elementow) 
np.linspace(0, 1)           # domyślnie 50 elementów
np.linspace(-3.5, 2.2, 42)  # [-3.5; 2.2) - jako przedział od -3.5 domknięty (włącznie) do 2.2 zamknięty (włącznie)

### generowanie losowych macierzy o rokładzie normalnym

In [ ]:
# generowanie losowych macierzy o rokładzie normalnym
N = np.random.normal()
# loc -> średnia, domyślnie 0; 
# scale -> odchylenie standardowe, domyślnie 1.0  
# size=None -> rozmiar macierzy, domyślnie None zwraca jedną liczbę
N = np.random.normal(loc=0.0, scale=1.0, size=None)  
N = np.random.normal(loc=1.3, scale=3.3, size=None)
N = np.random.normal(size=10)
N = np.random.normal(size=(7, 3))
N

### generowanie losowych macierzy o rokładzie normalnym N(0, 1)

Rozkład normalny ze średnią 0 i odchylenie standardowym 1.0

In [ ]:
# generowanie losowych macierzy o rokładzie normalnym N(0, 1)
S = np.random.randn()
S = np.random.randn(7)
S = np.random.randn(7, 3)
# S = np.random.randn((7, 3))  # TypeError: 'tuple' object cannot be interpreted as an integer
S

### generowanie losowych macierzy o rozkładzie jednostajnym

In [ ]:
# generowanie losowych macierzy o rozkładzie jednostajnym
U = np.random.uniform()
U = np.random.uniform(low=0.0, high=1.0, size=None)
U = np.random.uniform(low=-10, high=10, size=10)
U = np.random.uniform(low=-10, high=10, size=(7, 3))
U

### generowanie losowych macierzy o rozkładzie jednostajnym z przedziału [0; 1)

In [ ]:
# generowanie losowych macierzy o rozkładzie jednostajnym z przedziału [0; 1)
R = np.random.random()
R = np.random.random(size=10)
R = np.random.random((7, 3))
R

### generowanie losowych macierzy liczb czałkowitych o rozkładzie jednostajnym 

In [ ]:
# generowanie losowych macierzy liczb czałkowitych o rozkładzie jednostajnym 
I = np.random.randint(10)  # jedna liczba z przedziału [0; 10)
I = np.random.randint(low=10, high=12)  # np.random.randint(10, 12)
I = np.random.randint(1, 12, size=10)
I = np.random.randint(1, 12, size=(7, 3))
I

# Dostęp do elementów macierzy

In [ ]:
X = np.random.randn(7, 7)
X = np.round(X, 2)
X

### Index

In [ ]:
# Index
X[0]
X[0, 1]
X[:, 4]
X[1, :]
X[1:3]
X[1:3, 0:4]
# X[1:10]  !!!!
X[-1]
X[-2]
X[4:-1, 2:-1]
X[-3:-1, -4:-1]
# X[[1, 3], ]  X[[1, 3], [2, 4]]  # uwaga
X[::-1]
X[[3, 1, 0, 3, 3]]

In [ ]:
print(X)
print()
print(X[::-1])
print()
print(X[::-1, ::-1])

In [ ]:
V = X[1]
print(V)
print(V[::-1])

### Index warunkowy

In [ ]:
wynik = np.random.randint(10, 100, size=20)
wynik

In [ ]:
wynik[wynik>50]

In [ ]:
w = wynik > 50
w

In [ ]:
print(wynik[w])
print(wynik[~w])  # zaprzeczenie w (~ tylda)


### funkcja `np.where()`


In [ ]:
idx = np.where(w)  # np.where(wynik>50)
print(idx)
wynik[idx]  # wynik[[0, 2, 3... ]]

In [ ]:
print(np.where(w, 1, 0))
print(np.where(w, wynik, -wynik))

In [ ]:
np.where(wynik>50, np.sqrt(wynik), wynik ** 2)

# Operacje na macierzach

In [ ]:
X = np.random.randint(0, 10, size=(3, 4))
Y = np.random.randint(0, 10, size=(3, 4))
print(X)
print()
print(Y)

### Dodawanie / odejmowanie

In [ ]:
X + 3.14 
3.14 + X
X - 2.71
2.71 - X

In [ ]:
X + Y
np.add(X, Y)
# X + Y[0:2]  # ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 
X - Y
np.subtract(X, Y)

### Mnożenie

In [ ]:
10 * X
X * 10
X * Y
Y * X

In [ ]:
# mnożenie "algebraiczne"
print(X)
print()
print(Y)

# X.dot(Y)  # ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

##### Transpozycja

In [ ]:
# Transpozycja
print(X)
X.T.dot(Y)

In [ ]:
X.dot(Y.T)

In [ ]:
# mnożenie macierzy nie jest przemienne
print(X)
Z = Y.T
print()
print(Z)

In [ ]:
print(X.dot(Z))
print()
print(Z.dot(X))

### Macierz odwrotna

Macierz odwrotna do macierzy `A`, jest to taka macierz `B`, że po pomnożeniu macierzy `A`. przez macierz `B` dostaniemy element neutralny, czyli macierz `I` z `1` na przekątnej (diabonali) i `0`.

In [ ]:
A2d = np.random.randint(0, 10, size=(3, 3))
A2d_odwrotna = np.linalg.inv(A2d)
A2d_odwrotna

In [ ]:
print(np.round(A2d.dot(A2d_odwrotna)))
print()
print(np.round(A2d_odwrotna.dot(A2d)))

### Przekątna/Diagonala

In [ ]:
A2d.diagonal()

In [ ]:
# ślad macierzy
A2d.diagonal().sum()

# zmina kształtu macierzy

In [ ]:
C = np.random.randint(-10, 10, 24)
C

In [ ]:
C.reshape(6, 4)
C.reshape(4, 6)
# C.reshape(5, 2)  ValueError: cannot reshape array of size 24 into shape (5,2)
print(f"Warunek {sum(C.shape) == C.size}")
C.reshape(3, 2, 2, 2)

In [ ]:
C.reshape(6, -1)
C.reshape(-1, 6)

In [ ]:
C.reshape(4, -1)
C.reshape(-1, 4)
C.reshape(-1, 12)
C.reshape(-1, 1)

In [ ]:
print(C)
C1 = C.reshape(6, 4)
print()
print(C1)
print()
C1.flatten()

In [ ]:
C1

In [ ]:
C.reshape(3, 2, 2, 2).flatten()

# Zagadnienie regresji

In [ ]:
import numpy as np
import matplotlib.pyplot as plt


X = np.random.uniform(0, 10, size=(50))
noise = np.random.randn(X.size)
a, b = 3, 5
Y_true = a * X + b
Y = a * X + b + noise
Yt = Y.reshape(-1, 1)  # Y musi być wektorem kolu`mnowym

Xr = X.reshape(-1, 1)
Ib = np.ones(X.size).reshape(-1, 1)
Xc = np.concatenate([Ib, Xr], axis=1)


In [ ]:
est_param = np.linalg.inv(Xc.T.dot(Xc)).dot(Xc.T).dot(Yt)
b_est = est_param[0]
a_est = est_param[1]
print(f"Parametr a: wartość prawdziwa: {a} wartość estymowana: {a_est}")
print(f"Parametr b: wartość prawdziwa: {b} wartość estymowana: {b_est}")

In [ ]:
# funkcja estymowana
Y_est = a_est * X + b_est

In [ ]:
plt.figure(figsize=(10, 7))
plt.scatter(X, Y, alpha=0.7, s=1, label='obserwacje')
plt.plot(X, Y_true, color='red', label='funkcja teoretyczna', alpha=0.7)  # teoretyczna funkcja
plt.plot(X, Y_est, color='orange', label='funkcja estymowana', alpha=0.7)  # estymowana funkcja
plt.legend()
plt.show()

## Zadanie 1
Stwórz numpy array z wartościami od 1 do do 9, wyświetl, a następnie odwróć tę tablicę (pierwszy element zostaje ostatnim, itd.). 

In [54]:
import numpy as np

a = np.arange(1, 10)
print(a)
print(a[::-1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


## Zadanie 2
Stwórz następujący numpy array: [1, 23, 4, 31, 1, 1, 4, 23, 4, 1]; a następnie wypisz wszystkie unikalne (nie powtarzające się) elementy.

In [ ]:
import numpy as np

a = np.array([1, 23, 4, 31, 1, 1, 4, 23, 4, 1])
print(a)
print(np.unique(a))

## Zadanie 3
Stwórz macierz 3x3 (używając reshape) z wartościami od 2 do 10.

In [ ]:
import numpy as np

a = np.arange(2, 11).reshape(3, 3)
print(a)

## Zadanie 4
Stwórz tablicę z sześcioma losowymi wartościami z przedziału od 10 do 30.

In [ ]:
import numpy as np

a = np.random.randint(low=10, high=30, size=6)
print(a)

## Zadanie 5
Spośród tablicy wartości: [23, 45, 112, 150, 43, 254, 95, 8] wyfiltruj te, które są większe od 100.

In [ ]:
import numpy as np

a = np.array([23, 45, 112, 150, 43, 254, 95, 8])
print(a)
print(a[a > 100])
print(a[np.where(a > 100)])

## Zadanie 6
Stwórz poniższą macierz 4x4, a następnie:

1, 15, 4, 13, \
8, 21, 3, 12, \
11, 13, 11, 5, \
32, 13, 0, 2


* wyświetl element z drugiego wiersza i trzeciej kolumny, 
* oblicz jej wyznacznik,
* oblicz jej ślad (sumę elementów na głównej przekątnej),
* znajdź element największy i najmniejszy.

In [55]:
import numpy as np

a = np.array([[1, 15, 4, 13], [8, 21, 3, 12], [11, 13, 11, 5], [32, 13, 0, 2]])
print(a[1][2])
print(np.linalg.det(a))
print(a.diagonal().sum())
print(a.min(), a.max())

3
-19963.99999999999
35
0 32


<hr>

In [4]:
%%bash
jupyter nbconvert \
    --to html Algebra_liniowa.ipynb \
    --output-dir ./HTML

[NbConvertApp] Converting notebook Algebra_liniowa.ipynb to html
[NbConvertApp] Writing 678029 bytes to HTML/Algebra_liniowa.html
