### Zadanie 1


Stwórz numpy array z wartościami od 1 do do 9, wyświetl, a następnie odwróć tę tablicę (pierwszy element zostaje ostatnim, itd.). 

In [ ]:
import numpy as np

a = np.arange(1, 10)
print(a)
print(a[::-1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


### Zadanie 2

Stwórz następujący numpy array: [1, 23, 4, 31, 1, 1, 4, 23, 4, 1]; a następnie wypisz wszystkie unikalne (nie powtarzające się) elementy.

In [ ]:
import numpy as np

a = np.array([1, 23, 4, 31, 1, 1, 4, 23, 4, 1])
print(a)
print(np.unique(a))

[ 1 23  4 31  1  1  4 23  4  1]
[ 1  4 23 31]


### Zadanie 3

Stwórz macierz 3x3 (używając reshape) z wartościami od 2 do 10.

In [ ]:
import numpy as np

a = np.arange(2, 11).reshape(3, 3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Zadanie 4

Stwórz tablicę z sześcioma losowymi wartościami z przedziału od 10 do 30.

In [ ]:
import numpy as np

a = np.random.randint(low=10, high=30, size=6)
print(a)

[13 17 14 20 24 28]


### Zadanie 5

Spośród tablicy wartości: [23, 45, 112, 150, 43, 254, 95, 8] wyfiltruj te, które są większe od 100.

In [ ]:
import numpy as np

a = np.array([23, 45, 112, 150, 43, 254, 95, 8])
print(a)
print(a[a > 100])
print(a[np.where(a > 100)])

[ 23  45 112 150  43 254  95   8]
[112 150 254]
[112 150 254]


### Zadanie 6

Stwórz poniższą macierz 4x4, a następnie:
* wyświetl element z drugiego wiersza i trzeciej kolumny, 
* oblicz jej wyznacznik,
* oblicz jej ślad (sumę elementów na głównej przekątnej),
* znajdź element największy i najmniejszy.

$ \begin{bmatrix}
1 & 15 & 4 & 13 \\
8 & 21 & 3 & 12 \\
11 & 13 & 11 & 5 \\
32 & 13 & 0 & 2 
\end{bmatrix}  $

In [ ]:
import numpy as np

a = np.array([[1, 15, 4, 13], [8, 21, 3, 12], [11, 13, 11, 5], [32, 13, 0, 2]])
print(a[1][2])
print(np.linalg.det(a))
print(a.diagonal().sum())
print(a.min(), a.max())

3
-19963.99999999999
35
0 32


### Zadanie 7



Stwórz dowolną tablicę wartości, a następnie oblicz średnią i medianę.

In [ ]:
import numpy as np

a = np.array([5, 4, 3, 5, 3.5, 2, 1.34, 8])
print(a)
print(np.mean(a))
print(np.median(a))

[5.   4.   3.   5.   3.5  2.   1.34 8.  ]
3.98
3.75


### Zadanie 8

Stwórz dowolną tablicę wartości, a następnie je znormalizuj - tj. od każdego elementu tablicy odejmij średnią i podziel przez odchylenie standardowe.

In [ ]:
import numpy as np

a = np.array([5, 4, 3, 5, 3.5, 2, 1.34, 8])
print(a)
b = (a - np.mean(a)) / np.std(a)
print(b)

[5.   4.   3.   5.   3.5  2.   1.34 8.  ]
[ 0.52391807  0.0102729  -0.50337227  0.52391807 -0.24654968 -1.01701743
 -1.35602324  2.06485358]


### Zadanie 9

Stwórz funkcję, która przyjmuje dwa wektory (oba o tym samym wymiarze) w postaci numpy tablicy, a zwróci odległość euklidesową między nimi.

 $ d\left( p,q\right)   = \sqrt {\sum _{i=1}^{n}  \left( q_{i}-p_{i}\right)^2 } $

In [ ]:
def distance1(v1, v2):
    return np.sqrt(np.sum((v1 - v2) ** 2))


def distance2(v1, v2):
    return np.linalg.norm(v1 - v2)


a = np.array([1, 0, 1, 2, 3])
b = np.array([1, 2, -1, 0, 0])
print(distance1(a, b))
print(distance2(a, b))

4.58257569495584
4.58257569495584


### Zadanie 10

Korzystając z testu Shapiro-Wilka sprawdź, czy podana próba ma rozkład normalny: [0.873, 2.817, 0.121, -0.945, -0.055, -1.436, 0.360, -1.478, -1.637, -1.869] 


In [ ]:
from scipy.stats import shapiro

data = np.array([0.873, 2.817, 0.121, -0.945, -0.055, -1.436, 0.360, -1.478, -1.637, -1.869])
stat, p = shapiro(data)
print(stat, p)

if p > 0.05:
	  print("Rozkład normalny")
else:
	  print("Rozkład oddalony od krzywej Gaussa")

0.8951009511947632 0.19340917468070984
Rozkład normalny
